FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Wando API
Wando API - some init info

# Group Pages

## Init [/page/init]

### Get page init data [GET]

+ Response 200 (application/json)

        {
            "status"        : "success",
            "country"       : "US",
            "contactEmail"  : "info@products-i-want.com",
            "categoryData": [
                {
                    "id": 4760,
                    "name": "Cars and Accessories",
                    "clickout_url": "http:\/\/wow.com:8080\/web\/wando_frontend\/public?mainCat=Cars+and+Accessories"
                }, {
                    "id": 4761,
                    "name": "Clothing and Accessories",
                    "clickout_url": "http:\/\/wow.com:8080\/web\/wando_frontend\/public?mainCat=Clothing+and+Accessories"
                }
            ],
            "lang": {
            },
            "links": {
                "footer": {
                    "imprint": {
                        "url"   : "/page/imprint",
                        "title" : "Imprint"
                    },
                    "terms": {
                        "url"   : "/page/terms",
                        "title" : "Terms & Conditions"
                    },
                    "privacy": {
                        "url"   : "/page/privacy",
                        "title" : "Privacy Policy"
                    }
                },
                "product": {
                    "falz"      : "/product/falz",
                    "page"      : "/product/list",
                    "search"    : "/product/public"
                }
    }
        }
        
## Imprint [/page/imprint]

### Get imprint data [GET]

+ Response 200 (application/json)

        {
            "status"    : "success"
        }
        
## Terms [/page/terms]

### Get terms data [GET]

+ Response 200 (application/json)

        {
            "status"    : "success"
        }
        
## Privacy [/page/privacy]

### Get privacy data [GET]

+ Response 200 (application/json)

        {
            "status"    : "success"
        }
        
# Group Products


# Group Catalogue