FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# wando-api

Wando API test moqup

## Questions Collection [/page/init]

### Page initial call [GET]

+ Response 200 (application/json)

        {
            "status"    : "success",
            "foo"       : "bar"
        }