FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# wando-api

Wando API test moqup

## Questions Collection [/page]

### Page initial call [GET]

+ Response 200 (application/json)

        {
            'status'    : 'success',
            'foo'       : 'bar'
        }


## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }, {
                        "choice": "PHP",
                        "votes": 4096
                    }
                ]
            }, {
                "question": "Favourite tool?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Hammer",
                        "votes": 2048
                    }, {
                        "choice": "Drill",
                        "votes": 1024
                    }, {
                        "choice": "Power Hammer",
                        "votes": 1024
                    }, {
                        "choice": "test test test",
                        "votes": 1024
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language? - test update",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby",
                "PHP"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }, {
                        "choice": "PHP",
                        "votes": 0
                    }
                ]
            }
